- name: Create .clever-cloud directory
  file:
    path: "{{ clever_app_confdir }}"
    state: directory

- name: Fill the login file
  command: "clever login --token {{clever_token}} --secret {{clever_secret}}"
  args:
    chdir: "{{ clever_app_root }}"
    creates: "{{ clever_login_file }}"
  no_log: true

- name: Make sure no apps are already linked
  file:
    state: absent
    path: "{{ clever_app_root }}/.clever.json"

- name: Link app
  command: clever link {{ clever_app }}
  args:
    chdir: "{{ clever_app_root }}"
    creates: "{{ clever_app_root }}/.clever.json"
  environment:
    CONFIGURATION_FILE: "{{ clever_login_file }}"
